# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the trailing weighted means of streaming \emph{time series} data
NULL

rcpparma_hello_world <- function() {
    .Call(`_testrcpp_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_testrcpp_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_testrcpp_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_testrcpp_rcpparma_bothproducts`, x)
}

run_mean <- function(tseries, lambda, weightv = 0L) {
    .Call(`_testrcpp_run_mean`, tseries, lambda, weightv)
}

